name: build, lint and test

on:
  push:

jobs:
#  extract-bela-sysroot:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#    outputs:
#      digest: ${{ steps.build.outputs.digest }}
#    steps:
#      - uses: actions/checkout@v4
#      - run: make image
#      - run: sudo make sysroot.tar.gz

  publish-github-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          use: true
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
      - run: make image
      - run: sudo make sysroot.tar.gz

      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm
          tags: ghcr.io/${{ github.repository }}-cross


  build-lint-test:
    needs: [publish-github-container]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: setup qemu-binfmt
        run: docker run --rm --privileged multiarch/qemu-user-static --reset

          #- run: echo "${{ toJSON(needs.publish-github-container.outputs) }}"
          #- name: use built container
          #run: sed -i 's/^image = .*$/image = "${{ needs.publish-github-container.outputs.imageid }}"/' Cross.toml

      - run: cargo install cross
      - run: cross build --verbose
      - run: cross check --verbose
      - run: cross test --verbose
